### ISSUE TITLE
The argument type can't be assigned to the parameter type

### ISSUE THREAD

**Issue by kharitonovAL** [lcuis/search_choices#16]
Hi! 
I'm building a web app using flutter web and got this issue when trying to implement `search_choices`:

> error: The argument type 'List<DropdownMenuItem<dynamic>> (where DropdownMenuItem is defined in /Users/ak/Library/flutter/.pub-cache/git/flutter_web-cc38319841009fcbdf632d9b03aab18d28939438/packages/flutter_web/lib/src/material/dropdown.dart)' can't be assigned to the parameter type 'List<DropdownMenuItem<dynamic>> (where DropdownMenuItem is defined in /Users/ak/Library/flutter/packages/flutter/lib/src/material/dropdown.dart)'. (argument_type_not_assignable at [mc_web_app] lib/RequestsPage/AddEditRequestPage.dart:236)

My flutter doctor is:
```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale ru-RU)
    • Flutter version 1.19.0-4.1.pre at /Users/ak/Library/flutter
    • Framework revision f994b76974 (8 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ak/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

My `pubspec.yaml`:
```
name: mc_web_app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  protobuf: ^1.0.1
  provider: any

  service_worker: ^0.2.0
  googleapis_auth: ^0.2.3+5
  http: ^0.12.1
  intl: ^0.16.1
  search_choices: ^1.0.17

  firebase: any
  firebase_web: ^5.0.9

  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  test: ^1.14.6

dependency_overrides:
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web

  flutter_web:
    git:
      ref: cc38319
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web

  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

  firebase:
    git:
      url: https://github.com/FirebaseExtended/firebase-dart
```

My code is also below:
```dart

import 'package:search_choices/search_choices.dart';
...

  var _housesList = List<DropdownMenuItem<dynamic>>();

...

@override
  void initState() {
    if (!widget.editRequest) _db.getHouses().then((value) {
      var list = value.map((e) => DropdownMenuItem(value: e,
        child: Text('${e.city}, ${e.street}, ${e.houseNumber}'))).toList();
      _housesList = list;
    });
    super.initState();
  }

...

RaisedButton(
  child: Text('some text'),
    onPressed: () {
      SearchChoices.single(items: _housesList, onChanged: () { /*...*/ }); // ERROE GOES HERE
    },
  )
```

What this issue is about? I mean that I know that this issue appears when your `Widget` is not compatible with `flutter_web`, but [site](https://pub.dev/packages/search_choices) said that it's compatible with web.
